dist: bionic
language: python
python:
    - "3.6"

before_install:
    - sudo apt-get -y install wkhtmltopdf
    - cd server

install:
    - pip install -e .
    - pip install safety

script:
    - pip check
    - safety check
    - flake8 --config=../setup.cfg camcops_server
    - camcops_server self_test
