language: python
python:
    - "3.6"

before_install:
    - cd server

install:
    - pip install -e .
    - pip install safety

script:
    - safety check
    - flake8 --config=camcops_server/setup.cfg
    - camcops_server self_test
